version: '3.8'
services:
  nginx:
    image: nginx:stable-perl
    container_name: nginx-server
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./data/nginx:/etc/nginx
      # - ./certs:/etc/nginx/certs
      # depends_on:
      #   - app1
      #   - app2
    networks:
      - app_network

volumes:
  nginx: {}

networks:
  app_network:
    external: true
